import type { Metadata } from "next"

export const SITE_URL = "https://mailmind.nl"
export const SITE_NAME = "MailMind"
export const CONTACT_EMAIL = "rens@mailmind.nl"
export const DEFAULT_TITLE = "MailMind — AI-powered email automation for SMBs"
export const DEFAULT_DESCRIPTION =
  "MailMind is an autonomous AI email operator for SMBs. No chatbot, no autoresponder — a decision engine that classifies, decides, and acts with full transparency."

// Public pages. Used by the sitemap and by the proxy to recognise known routes.
// Update `lastModified` when a page's content changes.
export const publicRoutes = [
  { path: "/", title: "Home", lastModified: "2026-10-08", priority: 1 },
  { path: "/pricing", title: "Pricing", lastModified: "2026-10-08", priority: 0.9 },
  { path: "/security", title: "Security", lastModified: "2026-10-08", priority: 0.8 },
  { path: "/demo", title: "Request a demo", lastModified: "2026-04-03", priority: 0.9 },
  { path: "/about", title: "About", lastModified: "2026-10-08", priority: 0.7 },
  { path: "/contact", title: "Contact", lastModified: "2026-10-08", priority: 0.7 },
  { path: "/privacy", title: "Privacy policy", lastModified: "2026-10-08", priority: 0.5 },
  { path: "/login", title: "Log in", lastModified: "2026-04-03", priority: 0.3 },
] as const

export function absoluteUrl(path: string) {
  return new URL(path, SITE_URL).toString()
}

// Generated by app/opengraph-image.tsx. Referenced explicitly because a page-level
// `openGraph` object replaces the root one, including its images.
const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "MailMind — AI-powered email automation. Full control. Zero chaos.",
}

// Per-page metadata with a canonical URL. Open Graph fields are set explicitly
// because Next.js does not inherit og:url/og:title from the page title.
export function pageMetadata({
  title,
  description,
  path,
}: {
  title?: string
  description: string
  path: string
}): Metadata {
  const fullTitle = title ? `${title} | ${SITE_NAME}` : DEFAULT_TITLE
  return {
    ...(title ? { title } : {}),
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "en_US",
      siteName: SITE_NAME,
      url: path,
      title: fullTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE.url],
    },
  }
}
